### ISSUE TITLE
Must unit test ncrystal_endf2ncmat

### ISSUE THREAD

**Issue by dddijulio** [mctools/ncrystal#110]
ncrystal_endf2ncmat gives the following error for the latest NCrystal version:  NameError: name 'NCrystal' is not defined'

It works an earlier commit, for example: 10a5bf8ea91c009297417b146bd4151925309355

**Comment by tkittel** [comment]
Thanks for the report @dddijulio , this is actually a very easy fix.

```diff
diff --git a/ncrystal_python/ncrystal_endf2ncmat b/ncrystal_python/ncrystal_endf2ncmat
index 1881c7c..59731a3 100755
--- a/ncrystal_python/ncrystal_endf2ncmat
+++ b/ncrystal_python/ncrystal_endf2ncmat
@@ -83,7 +83,7 @@ def fixSysPathAndImportNCrystal( *, allowfail = False ):
         raise SystemExit(msg)
     return NCrystal
 ################################################################################################
-NC = fixSysPathAndImportNCrystal()
+NCrystal = fixSysPathAndImportNCrystal()
 
 import warnings
 import argparse
```

I have added it in 0f43ea3ef5e738d (which is not autolinked since I wrote #10 instead of #110 in the commit message :laughing:) which is in the develop branch for now.

I am going to rename and leave open the present issue, since we need to add a unit test somewhere exercising this script - so it doesn't happen again.

**Comment by tkittel** [comment]
A most basic test is being added in 3.7.0.

**Comment by tkittel** [comment]
Closing.
