### ISSUE TITLE
Compiler flag --frounding-math causes a "is not a constant expression" error in NCDefs.hh

### ISSUE THREAD

**Issue by marquezj** [mctools/ncrystal#63]
When compiling NCrystal 2.6.0 with gcc 7.5.0, the flag  --frounding-math causes a "is not a constant expression" error in NCDefs.hh:

ncrystal-src/ncrystal_core/include/NCrystal/NCDefs.hh:69:52:
 error: ‘(1.0e+0 / 1.0086649158800001e+0)’ is not a constant expression
 constexpr double const_inv_neutron_mass_amu = 1.0/const_neutron_mass_amu; // [amu]

The error seems to be caused by a bug in gcc:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96862

The current workaround is to compile without that flag.

**Comment by tkittel** [comment]
Thanks for documenting this here! For now I hope we can live with this, since we kind of are (and would want to) taking advantage of the compile-time FP math guaranteed by the standards. I hope affected users can compile with -fno-rounding-math (or simply stop adding -frounding-math).

Cheers,
Thomas
